# Not sure if we can plop this in and build it with clang, so for now, just
# compile with binaries built by gcc... 
ifeq ($(TOOLCHAIN),gcc)
DEPS += libapds
else # TOOLCHAIN != gcc

# libmspware is special because it has to be compiled by GCC, not Clang,
# even if the app is built with Clang
CFLAGS += -I$(LIB_ROOT)/libapds/src/include
LFLAGS += -L$(LIB_ROOT)/libapds/bld/gcc
LIBS += -lapds

endif # TOOLCHAIN != gcc

